version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./main.py:/app/main.py  # Assure-toi que ce fichier existe bien
    command: streamlit run main.py --server.address=0.0.0.0 --server.port=8000  # Commande pour démarrer Streamlit

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
